### ISSUE TITLE
TODO-20230801

### ISSUE THREAD

**Issue by Jinjin89** [Jinjin89/biodata#1]
# bioS4
- [ ] Add imvigor datasets
- [ ] try fix gene uppper or lower case issues

# Genes
- [x] get gene map(transform genes name into different format)
- [x] fun_gene2symbol: add the final symbol count
- [x] add db_kegg_v2
- [x] add db_reactome
- [x] db_kegg_metabolism, db_reactome_metabolism add classfications
- [ ] fix db_kegg_v2, remove NA genes, and remove space leading the class
- [ ] add ann_kegg and other annotation
- [ ] add tcga stemness
